force-app/main/default/objects/Contact_Team__c/Contact_Team__c.object-meta.xml
<CustomObject>
    <label>Contact Team</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Team__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Teams</relationshipLabel>
    <relationshipName>Contact_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTeamTriggerHandler.cls
public with sharing class ContactTeamTriggerHandler {
    
    public static void createContactShareRecords(List<Contact_Team__c> triggerNew, Map<Id, Contact_Team__c> triggerMap){
        if(triggerNew.isEmpty() && triggerMap.isEmpty()) {
            return;
        }
        List<ContactShare> contactShares = new List<ContactShare>();
        for(Contact_Team__c contactTeam : TriggerNew){
            ContactShare contactShare = new ContactShare(
                ContactId = contactTeam.Contact__c,
                UserOrGroupId = contactTeam.User__c,
                ContactAccessLevel = contactTeam.Access__c
            );
            contactShares.add(contactShare);
        }
        if(!contactShares.isEmpty()){
            insert contactShares;
        }
    }

    public static void updateContactShareRecords(List<Contact_Team__c> triggerNew, Map<Id, Contact_Team__c> triggerMap) {
        if(triggerNew.isEmpty() && triggerMap.isEmpty()) {
            return;
        }
        List<ContactShare> contactShares = new List<ContactShare>();
        for(Contact_Team__c contactTeam : TriggerNew){
            ContactShare contactShare = new ContactShare(
                ContactId = contactTeam.Contact__c,
                UserOrGroupId = contactTeam.User__c,
                ContactAccessLevel = contactTeam.Access__c
            );
            contactShares.add(contactShare);
            
        }
        if(!contactShares.isEmpty()){
            update contactShares;
        }
    }
}