force-app/main/default/objects/Contact_Team__c/Contact_Team__c.object-meta.xml
<CustomObject>
    <label>Contact Team</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Team__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Teams</relationshipLabel>
    <relationshipName>Contact_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTeamsController.cls
public with sharing class ContactTeamsController {
    
    @AuraEnabled(cacheable=true)
    public static List<Contact_Team__c> getContactShares(String contactId) {
        return [
            SELECT Id, Contact__c, User__c, Access__c, Role__c
            FROM Contact_Team__c
            WHERE Contact__c = :contactId
        ];
    }
    @AuraEnabled
    public static void deleteContactShares(String Id) {
        System.debug('Id '+Id);
        List<Contact_Team__c> contactTeam = [SELECT Id FROM Contact_Team__c WHERE Id = :Id LIMIT 1];
        try {
            delete contactTeam;
        } catch (DmlException e) {
            System.debug('An error occurred while deleting the account: ' + e.getMessage());
        }

    }

    public static List<Map<String, String>> getUserMap() {
        List<User> users = [SELECT Id, Name FROM USER WITH SECURITY_ENFORCED LIMIT 10];
        
        List<Map<String, String>> userOptions = new List<Map<String, String>>();
        for (User user: users) {
            userOptions.add(new Map<String, String>{'label' => user.Name, 'value' => user.Id});
        }

        return userOptions;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getSchemaData() {
        List<Map<String, String>> role = new List<Map<String, String>>();
        role.add(new Map<String, String>{'label' => 'Manager', 'value' => 'Manager'});
        role.add(new Map<String, String>{'label' => 'Agent', 'value' => 'Agent'});
        role.add(new Map<String, String>{'label' => 'Intern', 'value' => 'Intern'});
        
        List<Map<String, String>> access = new List<Map<String, String>>();
        access.add(new Map<String, String>{'label' => 'Read', 'value' => 'Read'});
        access.add(new Map<String, String>{'label' => 'Edit', 'value' => 'Edit'});

        List<Map<String, String>> user = getUserMap();

        Map<String, Object> schemaMap = new Map<String, Object>{
            'Role' => role,
            'Access'=> access,
            'User'=> user
        };

        return schemaMap;
    }
    
    @AuraEnabled
    public static void saveContactTeams(String contactTeams, Id contactId){
        try {
            if(!String.isBlank(contactTeams)){
                List<Contact_Team__c> newContactTeams = new List<Contact_Team__c>();
                List<ContactInfo> contactShares = (List<ContactInfo>)JSON.deserialize(contactTeams, List<ContactInfo>.class);
                
                for (ContactInfo contactTeam : contactShares) {
                    Contact_Team__c newContactTeam = new Contact_Team__c(
                        Id = !String.isBlank(contactTeam.Id) ? contactTeam.Id : null,
                        Contact__c = contactId, 
                        User__c = contactTeam.User, 
                        Access__c = contactTeam.Access,
                        Role__c = contactTeam.Role
                    );
                    newContactTeams.add(newContactTeam);
                }
                if(!newContactTeams.isEmpty()) {
                    upsert newContactTeams;
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static void shareContactWithUser(String contactId, String userId, String accessLevel) {
        ContactShare contactShare = new ContactShare();
        contactShare.ContactId = contactId;
        contactShare.UserOrGroupId = userId;
        contactShare.ContactAccessLevel = accessLevel;
        insert contactShare;
    }

    public class ContactInfo {
        public String Id;
        public String User;
        public String Role;
        public String Access;
    }
    
}